# Generated by Django 3.2.16 on 2022-11-30 16:32

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 23, 32, 22, 703453), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 23, 32, 22, 703453), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(null=True, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
