# Generated by Django 3.2.16 on 2022-11-30 16:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221130_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_of_questions',
        ),
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 23, 42, 19, 379094), verbose_name='Время жизни'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 23, 42, 19, 379094), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='проголосовавшие', to=settings.AUTH_USER_MODEL),
        ),
    ]
